[package]
name = "rust_hash_code_2020"
version = "0.1.0"
authors = ["enrico-kaack <e.kaack@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "RustHashCode"
path = "main.rs"
